version: '3.8'

networks:
  wpfleet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

services:
  mariadb:
    build:
      context: ./docker/mariadb
    container_name: wpfleet_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wpfleet_admin
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d:ro
      - ./data/logs/mariadb:/var/log/mysql
    networks:
      wpfleet:
        ipv4_address: 172.20.0.2
    ports:
      - "127.0.0.1:3306:3306"
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=500
      - --innodb_buffer_pool_size=256M
      - --innodb_log_file_size=64M
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: wpfleet_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      wpfleet:
        ipv4_address: 172.20.0.3
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  frankenphp:
    build:
      context: ./docker/frankenphp
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
    container_name: wpfleet_frankenphp
    restart: unless-stopped
    environment:
      DB_HOST: mariadb
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
      ACME_EMAIL: ${ACME_EMAIL}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    volumes:
      - ./data/wordpress:/var/www/html
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy/sites:/etc/caddy/sites
      - ./data/logs:/var/log
      - caddy_data:/data
      - caddy_config:/config
    networks:
      wpfleet:
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "wpfleet.frankenphp=true"
    mem_limit: ${FRANKENPHP_MEM_LIMIT:-2g}
    cpus: ${FRANKENPHP_CPU_LIMIT:-2}